# Generated by Django 4.0.6 on 2022-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
    ]
