# Generated by Django 4.0.6 on 2022-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_article_comments_article_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
